# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sportman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birth_place', models.CharField(max_length=400)),
                ('birth_date', models.DateField()),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaApp.Coach')),
            ],
        ),
    ]
