# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0003_events_sports'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sportman',
            new_name='Athlete',
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
