# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0004_auto_20160815_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='img_url',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
