# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0005_sport_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('sport_event', models.CharField(max_length=400)),
                ('result', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sport',
        ),
        migrations.AddField(
            model_name='athlete',
            name='img_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport',
            name='img_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='sportevent',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaApp.Sport'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sportevents',
            field=models.ManyToManyField(to='OlimpiColombiaApp.SportEvent'),
        ),
    ]
