# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0006_auto_20160820_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OlimpiColombiaApp.Sport'),
            preserve_default=False,
        ),
    ]
