# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0007_athlete_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportevent',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='video',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
