# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0008_auto_20160820_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sportevents',
            field=models.ManyToManyField(blank=True, to='OlimpiColombiaApp.SportEvent'),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='result',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
