# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0009_auto_20160820_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sportevents',
            field=models.ManyToManyField(blank=True, null=True, to='OlimpiColombiaApp.SportEvent'),
        ),
    ]
