# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0010_auto_20160820_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='sportevents',
        ),
        migrations.AlterField(
            model_name='sportevent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
