# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OlimpiColombiaApp', '0011_auto_20160820_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportevent',
            name='athletes',
            field=models.ManyToManyField(blank=True, null=True, to='OlimpiColombiaApp.Athlete'),
        ),
    ]
